from django.shortcuts import render

# Create your views here.
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:id>', views.product, name='product'),
    path('searchref', views.searchref, name='searchref'),
    path('filters', views.filters, name='filters'),
    path('create', views.create, name='create'),
    path('addcategory', views.addcategory, name='addcategory'),
    path('addbrand', views.addbrand, name='addbrand'),
    path('addmark', views.addmark, name='addmark'),
    path('addbulk', views.addbulk, name='addbulk'),
    path('commande', views.commande, name='commande'),
    path('orders', views.orders, name='orders'),
    path('orderitems/<int:id>', views.orderitems),
    path('dilevered/<int:id>', views.dilevered),
    path('paied/<int:id>', views.paied),
    path('marks/products/<int:id>', views.products),
    path('categories/products/<int:id>', views.productscategories),
    path('login', views.loginpage, name='loginpage'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('catalog', views.catalog, name='catalog'),
    path('salsemanorders/<str:str_id>', views.salsemanorders, name='salsemanorders'),
    path('logoutuser', views.logoutuser, name='logoutuser'),
    path('clients', views.clients, name='clients'),
    path('addclient', views.addclient, name='addclient'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('partners', views.partners, name='marques'),
    path('profile', views.profile, name='profile'),
    path('editinfoclient', views.editinfoclient, name='editinfoclient'),
    path('updatepassword', views.updatepassword, name='updatepassword'),
    path('developer', views.developer, name='developer'),
    path('create_product', views.create_product, name='create_product'),
    path('cart', views.cart, name='cart'),
    path('ordersforeach', views.ordersforeach, name='ordersforeach'),
    path('sitemap', views.sitemap, name='sitemap'),
    path('addtocart', views.addtocart, name='addtocart'),
    path('getcartitems', views.getcartitems, name='getcartitems'),
    path('removeitemincart', views.removeitemincart, name='removeitemincart'),
    path('edititemincart', views.edititemincart, name='edititemincart'),
    path('makeuserconnected', views.makeuserconnected, name='makeuserconnected'),
    path('getpdctfordash', views.getpdctfordash, name='getpdctfordash'),
    path('updateproduct', views.updateproduct, name='updateproduct'),
    path('listsamesmen', views.listsamesmen, name='listsamesmen'),
    path('listclients', views.listclients, name='listclients'),
    path('excel', views.excel, name='excel'),
    path('getsimilar', views.getsimilar, name='getsimilar'),
    # path('addtocart', views.addtocart, name='addtocart'),
    # path('addtocart', views.addtocart, name='addtocart'),
    # path('addtocart', views.addtocart, name='addtocart'),
    # path('addtocart', views.addtocart, name='addtocart'),
]